on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Connect to AWS Lightsail, extract file and delete the file
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: "44.211.199.96"
          username: ubuntu
          key: ${{ secrets.privat }}
          passphrase: ""
          port: 22
          script: |
            whoami
